package app.ripple.mesh.core

import org.json.JSONObject
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Test
import java.math.BigInteger
import java.security.KeyFactory
import java.security.KeyPair
import java.security.spec.ECPrivateKeySpec

/**
 * Conformance against protocol/test-vectors.json (generated by the Node reference
 * implementation). If these pass, Android and iOS agree byte-for-byte.
 */
class ProtocolVectorsTest {
    private val v: JSONObject = JSONObject(javaClass.getResourceAsStream("/test-vectors.json")!!.readBytes().toString(Charsets.UTF_8))

    private fun identityFromScalar(hex: String): Identity {
        val d = BigInteger(1, hex.hexToBytes())
        val priv = KeyFactory.getInstance("EC").generatePrivate(ECPrivateKeySpec(d, Crypto.p256Params))
        // Derive the public point via a scalar multiplication using the JDK: easiest is
        // to sign nothing and instead reconstruct from the known wire form in the vectors.
        val wire = when (hex) {
            v.getJSONObject("identities").getJSONObject("alice").getString("privateScalar") -> v.getJSONObject("identities").getJSONObject("alice").getString("publicKeyWire")
            v.getJSONObject("identities").getJSONObject("bob").getString("privateScalar") -> v.getJSONObject("identities").getJSONObject("bob").getString("publicKeyWire")
            else -> v.getJSONObject("directMessage").getString("ephemeralPublicKeyWire")
        }
        return Identity(priv, Crypto.publicKeyFromWire(wire.hexToBytes()))
    }

    private val alice by lazy { identityFromScalar(v.getJSONObject("identities").getJSONObject("alice").getString("privateScalar")) }
    private val bob by lazy { identityFromScalar(v.getJSONObject("identities").getJSONObject("bob").getString("privateScalar")) }

    @Test fun `node ids match`() {
        val ids = v.getJSONObject("identities")
        assertEquals(ids.getJSONObject("alice").getString("nodeId"), alice.nodeId.hex)
        assertEquals(ids.getJSONObject("bob").getString("nodeId"), bob.nodeId.hex)
        assertEquals(ids.getJSONObject("alice").getString("display"), alice.nodeId.display)
    }

    @Test fun `private scalars really match the public keys`() {
        // ECDH(alice.priv, bob.pub) == ECDH(bob.priv, alice.pub) only if both key pairs are consistent.
        assertArrayEquals(Crypto.ecdh(alice.privateKey, bob.publicKey), Crypto.ecdh(bob.privateKey, alice.publicKey))
    }

    @Test fun `announce encodes identically and verifies`() {
        val a = v.getJSONObject("announce")
        val payload = Announce(alice.publicKeyWire, a.getString("name")).encode()
        assertEquals(a.getString("payload"), payload.toHex())

        val full = Packet.decode(a.getString("fullPacket").hexToBytes())
        assertEquals(a.getString("unsignedBytes"), full.encodeUnsigned().toHex())
        assertEquals(a.getString("signingDigest"), full.signingDigest().toHex())
        assertTrue(Crypto.verify(alice.publicKey, full.encodeUnsigned(), full.signature))

        val d = a.getJSONObject("decoded")
        assertEquals(PacketType.ANNOUNCE, full.type)
        assertEquals(d.getInt("ttl"), full.ttl)
        assertEquals(d.getString("timestamp"), full.timestamp.toString())
        assertEquals(d.getString("source"), full.source.hex)
        assertTrue(full.destination.isBroadcast)

        val dec = Announce.decode(full.payload)
        assertEquals(a.getString("name"), dec.name)
    }

    @Test fun `our own signatures verify and match the vector's digest`() {
        val a = v.getJSONObject("announce")
        val ref = Packet.decode(a.getString("fullPacket").hexToBytes())
        val mine = PacketFactory.build(alice, PacketType.ANNOUNCE, ref.payload, ttl = ref.ttl, messageId = ref.messageId, timestamp = ref.timestamp)
        assertEquals(a.getString("unsignedBytes"), mine.encodeUnsigned().toHex())
        assertTrue(Crypto.verify(alice.publicKey, mine.encodeUnsigned(), mine.signature))
        assertEquals(64, mine.signature.size)
    }

    @Test fun `ttl decrement does not change the signing digest`() {
        val b = v.getJSONObject("broadcastMessage")
        val p = Packet.decode(b.getString("fullPacket").hexToBytes())
        assertEquals(b.getString("signingDigestAfterTtlDecrement"), p.withTtl(p.ttl - 1).signingDigest().toHex())
        assertTrue(Crypto.verify(alice.publicKey, p.withTtl(1).encodeUnsigned(), p.signature))
        assertEquals(b.getString("text"), String(p.payload, Charsets.UTF_8))
    }

    @Test fun `ecies matches the vector step by step`() {
        val d = v.getJSONObject("directMessage")
        val messageId = Packet.decode(d.getString("fullPacket").hexToBytes()).messageId
        val eph = identityFromScalar(d.getString("ephemeralScalar"))
        assertEquals(d.getString("ephemeralPublicKeyWire"), eph.publicKeyWire.toHex())

        val shared = Crypto.ecdh(eph.privateKey, bob.publicKey)
        assertEquals(d.getString("ecdhSharedX"), shared.toHex())
        assertEquals(d.getString("hkdfKey"), Crypto.hkdf(shared, messageId, Protocol.HKDF_INFO, 32).toHex())

        val box = Crypto.encryptWith(
            KeyPair(eph.publicKey, eph.privateKey), bob.publicKeyWire, messageId, alice.nodeId, bob.nodeId,
            d.getString("plaintext").toByteArray(Charsets.UTF_8), d.getString("nonce").hexToBytes(),
        )
        assertEquals(d.getString("eciesPayload"), box.toHex())

        val plain = Crypto.decrypt(bob.privateKey, messageId, alice.nodeId, bob.nodeId, box)
        assertEquals(d.getString("plaintext"), String(plain, Charsets.UTF_8))
    }

    @Test fun `direct packet from vector decrypts for bob and not alice`() {
        val d = v.getJSONObject("directMessage")
        val p = Packet.decode(d.getString("fullPacket").hexToBytes())
        assertTrue(p.isEncrypted)
        assertTrue(Crypto.verify(alice.publicKey, p.encodeUnsigned(), p.signature))
        assertEquals(d.getString("plaintext"), String(Crypto.decrypt(bob.privateKey, p.messageId, p.source, p.destination, p.payload), Charsets.UTF_8))
        try { Crypto.decrypt(alice.privateKey, p.messageId, p.source, p.destination, p.payload); fail("alice must not decrypt") } catch (_: Exception) {}
    }

    @Test fun `ack vector`() {
        val p = Packet.decode(v.getJSONObject("ack").getString("fullPacket").hexToBytes())
        assertEquals(PacketType.ACK, p.type)
        assertEquals(bob.nodeId.hex, p.source.hex)
        assertEquals(alice.nodeId.hex, p.destination.hex)
        assertTrue(Crypto.verify(bob.publicKey, p.encodeUnsigned(), p.signature))
        assertEquals(v.getJSONObject("directMessage").getString("fullPacket").hexToBytes().let { Packet.decode(it).messageIdHex }, p.payload.toHex())
    }

    @Test fun `fragmentation vectors`() {
        val f = v.getJSONObject("fragmentation")
        val frames = Fragmenter.fragment(f.getString("input").hexToBytes(), f.getInt("frameSize"), f.getInt("streamId"))
        val expected = f.getJSONArray("frames")
        assertEquals(expected.length(), frames.size)
        for (i in frames.indices) assertEquals(expected.getString(i), frames[i].toHex())

        val r = Reassembler()
        var out: ByteArray? = null
        for (fr in frames.shuffled()) r.push(fr)?.let { out = it }
        assertEquals(f.getString("input"), out!!.toHex())

        val small = f.getJSONObject("small")
        val sf = Fragmenter.fragment(small.getString("input").hexToBytes(), small.getInt("frameSize"), small.getInt("streamId"))
        assertEquals(small.getJSONArray("frames").getString(0), sf.single().toHex())
    }

    @Test fun `invalid packets are rejected`() {
        val bad = v.getJSONObject("invalid")
        for (key in listOf("wrongVersion", "truncated")) {
            try { Packet.decode(bad.getString(key).hexToBytes()); fail("$key should not decode") } catch (_: ProtocolException) {}
        }
        val tampered = Packet.decode(bad.getString("tamperedPayload").hexToBytes())
        assertFalse(Crypto.verify(alice.publicKey, tampered.encodeUnsigned(), tampered.signature))
    }
}
