import XCTest
import CryptoKit
@testable import Ripple

/// Conformance against protocol/test-vectors.json (generated by the Node reference
/// implementation). If these pass, iOS and Android agree byte-for-byte.
final class ProtocolVectorsTests: XCTestCase {
    private static let vectors: [String: Any] = {
        let url = Bundle(for: ProtocolVectorsTests.self).url(forResource: "test-vectors", withExtension: "json")!
        return try! JSONSerialization.jsonObject(with: Data(contentsOf: url)) as! [String: Any]
    }()
    private var v: [String: Any] { Self.vectors }
    private func obj(_ k: String) -> [String: Any] { v[k] as! [String: Any] }
    private func hex(_ o: [String: Any], _ k: String) -> Data { Data(hex: o[k] as! String)! }

    private lazy var alice = try! Identity(rawScalar: hex(obj("identities")["alice"] as! [String: Any], "privateScalar"))
    private lazy var bob = try! Identity(rawScalar: hex(obj("identities")["bob"] as! [String: Any], "privateScalar"))

    func testNodeIdsMatch() {
        let ids = obj("identities")
        XCTAssertEqual((ids["alice"] as! [String: Any])["nodeId"] as! String, alice.nodeId.hex)
        XCTAssertEqual((ids["alice"] as! [String: Any])["publicKeyWire"] as! String, alice.publicKeyWire.hex)
        XCTAssertEqual((ids["bob"] as! [String: Any])["nodeId"] as! String, bob.nodeId.hex)
        XCTAssertEqual((ids["alice"] as! [String: Any])["display"] as! String, alice.nodeId.display)
    }

    func testAnnounceEncodesIdenticallyAndVerifies() throws {
        let a = obj("announce")
        let payload = try Announce(publicKeyWire: alice.publicKeyWire, name: a["name"] as! String).encode()
        XCTAssertEqual(a["payload"] as! String, payload.hex)

        let full = try Packet.decode(hex(a, "fullPacket"))
        XCTAssertEqual(a["unsignedBytes"] as! String, full.encodeUnsigned().hex)
        XCTAssertEqual(a["signingDigest"] as! String, full.signingDigest().hex)
        XCTAssertTrue(Crypto.verify(alice.signing.publicKey, unsignedPacket: full.encodeUnsigned(), rawSignature: full.signature))

        let d = a["decoded"] as! [String: Any]
        XCTAssertEqual(full.type, .announce)
        XCTAssertEqual(Int(full.ttl), d["ttl"] as! Int)
        XCTAssertEqual(String(full.timestamp), d["timestamp"] as! String)
        XCTAssertEqual(full.source.hex, d["source"] as! String)
        XCTAssertTrue(full.destination.isBroadcast)
        XCTAssertEqual(try Announce.decode(full.payload).name, a["name"] as! String)
    }

    func testOwnSignaturesVerify() throws {
        let a = obj("announce")
        let ref = try Packet.decode(hex(a, "fullPacket"))
        let mine = try PacketFactory.build(alice, type: .announce, payload: ref.payload, ttl: ref.ttl, messageId: ref.messageId, timestamp: ref.timestamp)
        XCTAssertEqual(a["unsignedBytes"] as! String, mine.encodeUnsigned().hex)
        XCTAssertEqual(mine.signature.count, 64)
        XCTAssertTrue(Crypto.verify(alice.signing.publicKey, unsignedPacket: mine.encodeUnsigned(), rawSignature: mine.signature))
    }

    func testTTLDecrementKeepsDigest() throws {
        let b = obj("broadcastMessage")
        let p = try Packet.decode(hex(b, "fullPacket"))
        XCTAssertEqual(b["signingDigestAfterTtlDecrement"] as! String, p.withTTL(p.ttl - 1).signingDigest().hex)
        XCTAssertTrue(Crypto.verify(alice.signing.publicKey, unsignedPacket: p.withTTL(1).encodeUnsigned(), rawSignature: p.signature))
        XCTAssertEqual(String(data: p.payload, encoding: .utf8), b["text"] as? String)
    }

    func testECIESMatchesStepByStep() throws {
        let d = obj("directMessage")
        let messageId = try Packet.decode(hex(d, "fullPacket")).messageId
        let eph = try P256.KeyAgreement.PrivateKey(rawRepresentation: hex(d, "ephemeralScalar"))
        XCTAssertEqual(d["ephemeralPublicKeyWire"] as! String, eph.publicKey.x963Representation.hex)

        let shared = try eph.sharedSecretFromKeyAgreement(with: bob.agreement.publicKey)
        XCTAssertEqual(d["ecdhSharedX"] as! String, shared.withUnsafeBytes { Data($0) }.hex)
        let key = Crypto.deriveKey(shared, messageId: messageId)
        XCTAssertEqual(d["hkdfKey"] as! String, key.withUnsafeBytes { Data($0) }.hex)

        let box = try Crypto.encrypt(ephemeral: eph, recipientWire: bob.publicKeyWire, messageId: messageId, source: alice.nodeId, destination: bob.nodeId,
                                     plaintext: Data((d["plaintext"] as! String).utf8), nonce: try AES.GCM.Nonce(data: hex(d, "nonce")))
        XCTAssertEqual(d["eciesPayload"] as! String, box.hex)

        let plain = try Crypto.decrypt(recipient: bob.agreement, messageId: messageId, source: alice.nodeId, destination: bob.nodeId, payload: box)
        XCTAssertEqual(String(data: plain, encoding: .utf8), d["plaintext"] as? String)
    }

    func testDirectPacketDecryptsForBobNotAlice() throws {
        let d = obj("directMessage")
        let p = try Packet.decode(hex(d, "fullPacket"))
        XCTAssertTrue(p.isEncrypted)
        XCTAssertTrue(Crypto.verify(alice.signing.publicKey, unsignedPacket: p.encodeUnsigned(), rawSignature: p.signature))
        let plain = try Crypto.decrypt(recipient: bob.agreement, messageId: p.messageId, source: p.source, destination: p.destination, payload: p.payload)
        XCTAssertEqual(String(data: plain, encoding: .utf8), d["plaintext"] as? String)
        XCTAssertThrowsError(try Crypto.decrypt(recipient: alice.agreement, messageId: p.messageId, source: p.source, destination: p.destination, payload: p.payload))
    }

    func testAckVector() throws {
        let p = try Packet.decode(hex(obj("ack"), "fullPacket"))
        XCTAssertEqual(p.type, .ack)
        XCTAssertEqual(p.source, bob.nodeId)
        XCTAssertEqual(p.destination, alice.nodeId)
        XCTAssertTrue(Crypto.verify(bob.signing.publicKey, unsignedPacket: p.encodeUnsigned(), rawSignature: p.signature))
        XCTAssertEqual(p.payload, try Packet.decode(hex(obj("directMessage"), "fullPacket")).messageId)
    }

    func testFragmentationVectors() {
        let f = obj("fragmentation")
        let frames = Fragmenter.fragment(hex(f, "input"), frameSize: f["frameSize"] as! Int, streamId: UInt16(f["streamId"] as! Int))
        let expected = f["frames"] as! [String]
        XCTAssertEqual(frames.map(\.hex), expected)

        let r = Reassembler()
        var out: Data?
        for fr in frames.shuffled() { if let p = r.push(fr) { out = p } }
        XCTAssertEqual(out?.hex, f["input"] as? String)

        let small = f["small"] as! [String: Any]
        let sf = Fragmenter.fragment(hex(small, "input"), frameSize: small["frameSize"] as! Int, streamId: UInt16(small["streamId"] as! Int))
        XCTAssertEqual(sf.map(\.hex), small["frames"] as! [String])
    }

    func testInvalidPacketsRejected() throws {
        let bad = obj("invalid")
        XCTAssertThrowsError(try Packet.decode(hex(bad, "wrongVersion")))
        XCTAssertThrowsError(try Packet.decode(hex(bad, "truncated")))
        let tampered = try Packet.decode(hex(bad, "tamperedPayload"))
        XCTAssertFalse(Crypto.verify(alice.signing.publicKey, unsignedPacket: tampered.encodeUnsigned(), rawSignature: tampered.signature))
    }
}
