#!/usr/bin/env node
'use strict';

// Extract the literal-as-key SwiftUI strings used by Ripple's UI. This deliberately
// has no npm dependencies so translators and CI can run it with plain Node.
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..', '..');
const uiDir = path.join(root, 'ios', 'Ripple', 'UI');
const output = path.join(root, 'ios', 'Ripple', 'Resources', 'en.lproj', 'Localizable.strings');
const calls = '(?:Text|Label|Button|TextField|SecureField|LabeledContent)';
const patterns = [
  new RegExp(`\\b${calls}\\s*\\(\\s*"((?:\\\\.|[^"\\\\])*)"`, 'g'),
  /\.navigationTitle\s*\(\s*"((?:\\.|[^"\\])*)"/g,
];

function decodeSwiftLiteral(body) {
  return body.replace(/\\(n|r|t|"|\\)/g, (_, escaped) => ({
    n: '\n', r: '\r', t: '\t', '"': '"', '\\': '\\',
  })[escaped]);
}

function stringsEscape(value) {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\r/g, '\\r')
    .replace(/\n/g, '\\n');
}

const values = new Set();
for (const name of fs.readdirSync(uiDir).filter((name) => name.endsWith('.swift')).sort()) {
  const source = fs.readFileSync(path.join(uiDir, name), 'utf8');
  for (const pattern of patterns) {
    pattern.lastIndex = 0;
    for (let match; (match = pattern.exec(source)) !== null;) {
      // Interpolated strings are runtime values, not stable localization keys.
      if (match[1].includes('\\(')) continue;
      values.add(decodeSwiftLiteral(match[1]));
    }
  }
}

const lines = [
  '/* Generated by tools/i18n/extract-ios.js. Literal English text is the key. */',
  '',
  ...Array.from(values).sort().map((value) => {
    const escaped = stringsEscape(value);
    return `"${escaped}" = "${escaped}";`;
  }),
  '',
];
fs.mkdirSync(path.dirname(output), { recursive: true });
fs.writeFileSync(output, lines.join('\n'), 'utf8');
console.log(`Wrote ${path.relative(root, output)} (${values.size} strings)`);
